version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - GITHUB_AUTH_TOKEN=${GITHUB_BEARER_TOKEN}
      - ZENHUB_TOKEN=${ZENHUB_TOKEN}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '127.0.0.1:5432:5432'
