version: '3'
services:
  web:
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    env_file: .env
    environment:
      DB_HOST: db
    command: flask run --host=0.0.0.0 --port=5000
  db:
    image: postgres:10.5-alpine
    ports:
    - '127.0.0.1:5433:5432'

