version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${FLASK_PORT}:5000"
    env_file: qualitas.env
    environment:
      FLASK_PORT: 5000
    command: gunicorn wsgi:app --bind 0.0.0.0:${FLASK_PORT} --reload --log-level=debug
    links:
      - db
  db:
    image: postgres:11-alpine
    ports:
      # Expose to local host for pgadmin access
      - '127.0.0.1:5433:5432'
