version: '3'
services:
  web:
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgres://postgres:@db/qualitas_db
    command: flask run --host=0.0.0.0 --port=5000
  db:
    image: postgres:9.6-alpine
    ports:
    - '127.0.0.1:5433:5432'

