version: '3'
services:
  web:
    build: ./
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: postgres:10.5-alpine
    environment:
      - DATABASE_URL=postgres://postgres:@db/testing
    ports:
      - '127.0.0.1:5432:5432'
