version: '3'
services:
  web:
    build: ./
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - ZENHUB_TOKEN=${ZENHUB_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: postgres:11-alpine
    ports:
      - '127.0.0.1:5432:5432'
