version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - GITHUB_BEARER_TOKEN=${GITHUB_BEARER_TOKEN}
      - ZENHUB_TOKEN=${ZENHUB_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '127.0.0.1:5432:5432'
