version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:202004-01

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and unit tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results
  build:
    environment:
      IMAGE_NAME: openstax/qualitas-server
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            revision=$(git --git-dir=.git rev-parse --short HEAD)
            echo $revision
            branch=$CIRCLE_BRANCH
            docker build -t $IMAGE_NAME:$revision .

workflows:
  version: 2
  build-and-run-tests:
    jobs:
      - test
      - build:
          requires:
            - test