---
version: 2.0
jobs:
  test-qualitas:
    docker:
      - image: circleci/python:3.8
        environment:
          GITHUB_USER: $GITHUB_USER
          GITHUB_PASSWORD: $GITHUB_PASSWORD
          ZENHUB_TOKEN: $ZENHUB_TOKEN
          GITHUB_BEARER_TOKEN: $GITHUB_BEARER_TOKEN
          DB_HOST: 127.0.0.1
          DB_NAME: test
          DB_PASSWORD: $DB_PASSWORD
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: $DB_PASSWORD
    steps:
      - checkout

      - run:
          name: install dependenciies
          command: pip install -r requirements.txt

      - run:
          name: run database migrations
          command: alembic upgrade head

workflows:
  version: 2
  run-tests:
    jobs:
      - test-qualitas
      
      
          
          
        
