version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: openstax/qualitas-server
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  
  test:
    machine:
      image: ubuntu-1604:202004-01

    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      TEST_RESULTS: /tmp/test-results/junit.xml

    steps:
      - checkout
      # Permissions errors occurred with 0775 due to
      # docker user not having permissions over this folder.
      - run: mkdir -p -m=0777 $TEST_RESULTS_DIR

      - run:
          name: Run integration and unit tests
          command: |
            ./scripts/tests.ci.sh

      - store_artifacts:
          path: /tmp/test-results/junit.xml
          destination: test-reports

      - store_test_results:
          path: /tmp/test-results
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            revision=$(git --git-dir=.git rev-parse --short HEAD) >> $BASH_ENV
            echo "export REVISION=$(git --git-dir=.git rev-parse --short HEAD)" >> $BASH_ENV
            docker build -t $IMAGE_NAME:$revision .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  # Project settings are set to only build PRs, but they will also still occur of main and tags.
  publish-pr:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$CE_DOCKERHUB_TOKEN" | docker login -u "$CE_DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$REVISION
  publish-main:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            TAG$(date '+%Y%m%d.%H%M%S')
            echo "$CE_DOCKERHUB_TOKEN" | docker login -u "$CE_DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$TAG

workflows:
  version: 2
  build-and-run-tests:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish-pr:
          requires:
            - build
      - publish-main:
          requires:
            - test
          filters:
            branches:
              only: master
          