"""added last_edited_by_id field to WikiPage model

Revision ID: eea65221a891
Revises: f6cdcb5f29d0
Create Date: 2018-11-21 16:08:54.613168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea65221a891'
down_revision = 'f6cdcb5f29d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_page', sa.Column('last_updated_by_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_wiki_page_id'), 'wiki_page', ['id'])
    op.create_foreign_key(op.f('fk_wiki_page_last_updated_by_id_users'), 'wiki_page', 'users', ['last_updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_wiki_page_last_updated_by_id_users'), 'wiki_page', type_='foreignkey')
    op.drop_constraint(op.f('uq_wiki_page_id'), 'wiki_page', type_='unique')
    op.drop_column('wiki_page', 'last_updated_by_id')
    # ### end Alembic commands ###
